Feature/readme
bancolombia/scaffold-clean-architecture pull request #91
Opened 2020-09-11 00:59 UTC by JuanDGiraldoM

Styling the readme and updating the plugin version

2020-09-14 14:17 UTC, santitigaga requested changes

2020-09-14 14:17 UTC, santitigaga commented on src/main/resources/structure/root/readme.md.mustache
> +![Clean Architecture](https://miro.medium.com/max/140# Proyecto Base Implementando Clean Architecture
Fix url

2020-09-14 14:17 UTC, santitigaga commented on src/main/resources/structure/root/readme.md.mustache
> +0/1*ZdlHz8B0-qu9Y-QO3AXR_w.png)
Fix Entry Point Content

2020-09-15 16:57 UTC, JuanDGiraldoM reviewed
All reviewed

2020-09-15 20:23 UTC, santitigaga approved these changes

2020-09-15 20:23 UTC, merged